### ISSUE TITLE
singlepage app generator does not generate a valid single page app.

### ISSUE THREAD

**Issue by jaredbro** [reachlocal/generator-ligermobile#20]
When generating a new app and selecting to generate a SinglePage app, the resulting app does not run correctly.  This results in an error stating that app.json is invalid, because the SinglePage app in the generated app.json doesn't have the correct page definition to load.

**Comment by ligerjohn** [comment]
This is a bug in LigerMobile's iOS native code: reachlocal/liger-ios#106. The code generated is valid.

Closing this issue.

(The requirement that the args mustn't be empty for a root page stems from an old version of LigerMobile that isn't true anymore, but the assert survived.)
